src/recepcion/urls.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""Urls para la aplicación de RECEPCION."""

from django.conf.urls.defaults import patterns, url
from motor.models import Hotel

urlpatterns = patterns('',
    url(r'^listado-hoteles/$', 'django.views.generic.list_detail.object_list',
        {'queryset': Hotel.objects.all(),
         'template_name': 'recepcion/hoteles.html'},
        name='listado-hoteles'),
    url(r'^listado-contratos/$','django.views.generic.list_detail.object_list',
        {'queryset': Hotel.objects.all(),
         'template_name': 'recepcion/hotel_list.html'},
            name="listado-contratos"),
    url(r'contrato-hotel/(?P<slug>[\w_-]+)/$', 'django.views.generic.list_detail.object_detail',
        {'queryset': Hotel.objects.all(),
         'template_name': 'recepcion/contrato_hotel.html',
         'slug_field': 'slug'},
        name="contrato-hotel"),
    url(r'^disponibilidad2ad/$', 'recepcion.views.disponibilidad_2ad', name="disponibilidad-2ad"),
    url(r'^disponibilidad2ad1n/$', 'recepcion.views.disponibilidad_2ad_1n', name="disponibilidad-2ad-1n"),
    url(r'^disponibilidad/$', 'recepcion.views.disponibilidad', name="disponibilidad"),
    )

src/urls.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from motor.models import Hotel
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    url(r'^$', direct_to_template, {'template':'index.html'},
                                    name='index-recepcion'),
    (r'^hotel/', include('hotel.urls')),
    (r'^recepcion/', include('recepcion.urls')),
    (r'^motor/', include('motor.urls')),
    (r'^contacto/', include('contacto.urls')),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)


urlpatterns += patterns('',
    url (
        r'^faq/$',
        'faq.views.faq_list_by_group',
        name = 'faq',
    ),
                       )

urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),
)
# We're going to use the Django server in development, so we'll server
# also the estatic content.
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':'./media/'}),
    )

src/motor/models.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""Definición de la Base de datos para el motor de reservas.
"""
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from motor.core.interval import overlaps_in_range, inside
from motor.core.inventario import crear_inventario, crear_inventario_condicion


class TipoHabitacionManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug = slug)

class RegimenManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug = slug)

class TipoHabitacion(models.Model):
    """Define los tipos de habitacion posibles. Una habitación se define
    por su ocupación mínima y máxima.

    Si una habitación es de un tipo base indica que habrá un contrato con
    cupo y precios especiales para este tipo de habitación

    """

    #TODO Añadir anidamento de tipos

    objects  = TipoHabitacionManager()

    slug = models.SlugField(max_length=20, unique=True)
    descripcion = models.CharField(max_length=100)
    minimo = models.PositiveSmallIntegerField(default=2, help_text = "Ocupación mínima Adultos")
    maximo = models.PositiveIntegerField(default=4, help_text= "Ocupación máxima adultos")
    children = models.IntegerField(default=2, help_text= "Máxima ocupación de niños")
    maximo_total = models.IntegerField(default=5, help_text = "Ocupación máxima entre adultos y niños")
    is_base = models.BooleanField(help_text = "Marcar si es un referencia para cupo y precio")
    is_individual = models.BooleanField(default=False, help_text="Indica si se refere a ocupación individual")
    parent = models.ForeignKey('self', blank=True, null=True, related_name='subtipos',  limit_choices_to={'is_base': True})


    class Meta:
        verbose_name = "Tipo de Habitación"
        verbose_name_plural = "Tipos de Habitación"

    def __unicode__(self):
        return self.descripcion

    def clean(self):
        if self.minimo > self.maximo:
            raise ValidationError('La ocupación mínima debe ser menor que la máxima')
        if self.is_individual:
            self.minimo = 1
            self.maximo = 1
        if self.is_base and (not self.parent==None):
            raise ValidationError('Una habitación base no puede estar ligada a otra')
        if not self.is_base and (self.maximo != self.minimo):
            raise ValidationError('No puede existir rango para habitaciones que no son de tipo base')
        if not self.is_base and (self.parent.maximo < self.minimo):
            raise ValidationError('El máximo no puede superar al de la habitación base')

    def is_valid(self, adultos, ninyos):
        """Dado un número de adultos y niños determina
        si pueden estar en la habitación"""
        return (adultos<=self.maximo) and (adultos>=self.minimo) \
                and (ninyos>=0) and (ninyos<=self.children) \
                and (self.maximo_total >= (adultos+ninyos))

    def natural_key(self):
        return (self.slug, )


class Regimen(models.Model):
    """Definición del régimien alimenticio"""
    slug = models.SlugField(max_length=10, unique=True)
    descripcion = models.CharField(max_length=100)
    is_base = models.BooleanField(help_text="Marcar si es una referencia para cupo y precio")
    parent = models.ForeignKey('self', blank=True, null=True, related_name='subtipos')

    objects = RegimenManager()

    class Meta:
        verbose_name="Régimen"
        verbose_name_plural="Regimenes"

    def __unicode__(self):
        return self.descripcion

    def clean(self):
        if self.is_base and (not self.parent==None):
            raise ValidationError('Una habitación base no puede estar ligada a otra')

    def natural_key(self):
        return (self.slug, )

class Hotel(models.Model):
    """Definición del hotel.
    Las habitaciones y régimenes se definen a partir de las condiciones del contrato
    """

    slug = models.SlugField(max_length=20, unique=True)
    nombre = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Hotel"
        verbose_name_plural = "Hoteles"

    def __unicode__(self):
        return self.nombre

    def natural_key(self):
        return (self.slug, )

    def get_contrato_html(self, plantilla="contrato.html"):
        """Devuelve la representación del contrato del hotel
        en formato html"""
        from motor.core.contrato import get_contratos
        return get_contratos(self.pk)

class Contrato(models.Model):
    """Contrato.
    Un contra siempre tiene unas fiechas fijas y se refiere
    a un hotel en concreto. La desactivación de un contrato implica que las
    habitaciones del hotel dejan de estar disponibles.

    Importante: para un mismo hotel los contratos no pueden solaparse
    """

    #TODO añadir mercado

    nombre = models.CharField(max_length=100)
    fecha_inicio = models.DateField()
    fecha_fin    = models.DateField()
    hotel        = models.ForeignKey(Hotel)
    activo       = models.BooleanField(default=False,
                                       help_text="Marque com activo para que se genere el cupo")
    revisado     = models.BooleanField(default=False,
                                       help_text="Marque como revisado cuando esté acabado")

    class Meta:
        verbose_name= "Contrato"
        verbose_name_plural = "Contratos"

    def __unicode__(self):
        return "%s [%s]" % (self.nombre, self.hotel)

    def save(self, *k, **kw):
        super(Contrato, self).save(*kw, **kw)

    def clean(self):
        if self.fecha_fin < self.fecha_inicio:
            raise ValidationError("La fecha fin debe ser mayor que la inicial")
        contratos = Contrato.objects.filter(hotel=self.hotel, activo=True)
        if self.id:
            contratos = contratos.exclude(pk=self.pk)
        if overlaps_in_range(contratos, self.fecha_inicio, self.fecha_fin,
                                         lambda x: (x.fecha_inicio, x.fecha_fin)):
            raise ValidationError("Los contratos para este hotel se solapan")
        if not self.revisado and self.activo:
            raise ValidationError("Un contrato no puede ser activado si no se marca como revisado")

class CondicionesContrato(models.Model):
    """Las condiciones del contrato una vez establecidas y con el contrato
    validado no se pueden modificar, ya que afectaría a cupo y precios."""

    contrato = models.ForeignKey(Contrato)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    regimen = models.ForeignKey(Regimen, limit_choices_to={'is_base': True})
    tipo_habitacion = models.ForeignKey(TipoHabitacion, limit_choices_to={'is_base': True})
    precio = models.DecimalField(max_digits = 5, decimal_places = 2, help_text="Precio por persona y noche")
    is_apartamento = models.BooleanField(default=False, help_text="Marcado aplica sólo precio por noche")
    cupo = models.PositiveSmallIntegerField()
    is_paro_ventas = models.BooleanField(default=False,
                                        help_text="Indique si es un paro de ventas")
    is_venta_libre = models.BooleanField(default=False,
                                         help_text="Indique si es venta libre (sin cupo)")
    is_cupo_generado = models.BooleanField(default=False, editable=False)

    def clean(self):
        """
        La fecha de inicio debe ser mayor que la final.
        Las fectas debe estar dentro del rango del contrato
        Las fechas no deben solaparse para un mismo tipo y régimen
        El precio debe ser mayor que cero.
        """
        if self.fecha_fin < self.fecha_inicio:
            raise ValidationError("La fecha fin debe ser mayor que la inicial")
        condiciones = CondicionesContrato.objects.filter(contrato=self.contrato,
                                                         regimen=self.regimen,
                                                         tipo_habitacion=self.tipo_habitacion)
        if self.id:
            condiciones = condiciones.exclude(pk=self.pk)
        if overlaps_in_range(condiciones, self.fecha_inicio, self.fecha_fin,
                                         lambda x: (x.fecha_inicio, x.fecha_fin)):
            raise ValidationError("Las condiciones para este contrato se solapan")
        if self.precio <=0 and not self.is_paro_ventas:
            raise ValidationError("El precio debe ser mayor que cero si no hay paro de ventas")

# suplementos -----------------------------------------------------------------

class SuplementoRegimen(models.Model):
    """Define los suplementos de régimen que se aplicarán al contrato en las fechas
    determinadas tomando como base el régimen padre

    suplemento = regimen.precio + suplemento.precio + regimen.precio*porcentaje%

    Por ejemplo, si el precio por pesona y noche en MP para habitación doble std es 20
    y tenemos un suplemento de pensión completa de 10 + 5% el total sería

    total = 20 + 10 + 20*0.05 = 31

    Si no hay suplementos de régimen definidos se supone que dicho régimen no está
    definido para ese contrato en esas fechas.

    """
    hotel = models.ForeignKey(Hotel)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    regimen = models.ForeignKey(Regimen, limit_choices_to={'is_base': False})
    precio = models.DecimalField("sobre precio", max_digits = 5, decimal_places = 2, help_text="Suplemento absoluto sobre persona y noche")
    class Meta:
        verbose_name = u"Suplemento de Régimen"
        verbose_name_plural = u"Suplementos de Régimen"

    def clean(self):
        """Las fechas para un mismo contrato y regimen no pueden solaparse"""
        if self.fecha_fin < self.fecha_inicio:
            raise ValidationError("La fecha fin debe ser mayor que la inicial")
        condiciones = SuplementoRegimen.objects.filter(hotel=self.hotel,
                                                         regimen=self.regimen)

src/recepcion/forms.py
#!/usr/bin/env python
#-*- coding: UTF-8 -*-

from django import forms
from motor.models import Hotel
from captcha.fields import CaptchaField

"""Definición de los formularios del front-end"""
MAX_ROOMS = 1 # por ahora el motor no admite distribución
MAX_ADULTS = 4
MAX_NINS = 3
MAX_AGE = 12

class BuscarForm(forms.Form):
    """Formulario de búsqueda"""
    hotel = forms.ModelChoiceField(queryset=Hotel.objects.all().order_by('nombre') , empty_label="(Todos)", required=False)
    fecha_llegada = forms.DateField(help_text="Fecha de entrada al hotel", input_formats=('%d/%m/%Y',))
    fecha_salida  = forms.DateField(help_text="Fecha de salida del hotel", input_formats=('%d/%m/%Y',))
    habitaciones = forms.TypedChoiceField(choices=[(x,x) for x in range(1,MAX_ROOMS+1)] ,coerce=int)
    captcha = CaptchaField()
    def __init__(self, *args, **kwargs):
        super(BuscarForm, self).__init__(*args, **kwargs)
        for i in range(1, MAX_ROOMS+1):
            self.fields['adultos_d%s' % i] = forms.TypedChoiceField(choices = [(x,x) for x in range(1, MAX_ADULTS+1)], coerce=int)
            self.fields['nins_d%s' %i] = forms.TypedChoiceField(choices = [(x,x) for x in range(0, MAX_NINS+1)],
                                                                coerce =int,
                                                                widget = forms.Select( attrs={'class':'nins'} ))
            for j in range(1, MAX_NINS+1):
                self.fields['edad_nin%s_d%s' % (j, i)] = forms.TypedChoiceField(choices = [(x,x) for x in range(0, MAX_AGE+1)], coerce=int)

src/templates/recepcion/forms.py
#!/usr/bin/env python
#-*- coding: UTF-8 -*-

from django import forms
from motor.models import Hotel

class BuscarForm(forms.Form):
    """Buscador de disponibilidad"""
    hotel = forms.ModelChoiceField(queryset=Hotel.objects.all().order_by('nombre'),
                                   empty_label="(Todos los hoteles)")

src/recepcion/views.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""
Vistas para el testeo de disponibilidad
"""

from motor.core.tarificador import Disponibilidad
from django.views.generic.simple import direct_to_template
from motor.core.consulta import Consulta
from datetime import date, timedelta
from forms import BuscarForm
LIMITE_BEBES = 2 # se consideran bebés los niños menores de 2 años

def disponibilidad_2ad(request):
    """Ejemplo de disponibilidad para dos adultos"""
    consulta = Consulta(date.today()+timedelta(days=5),
                            noches=5,
                            adultos = 2,
                            ninyos = 0,
                           )
    dispo = Disponibilidad(consulta)
    dispo.obtener_disponibilidad()
    form = BuscarForm()
    return direct_to_template(request, template='recepcion/disponibilidad.html',
                              extra_context={'dispo': dispo, 'consulta':consulta,
                                             'form':form})

def disponibilidad_2ad_1n(request):
    """Ejemplo de disponibilidad de dos adultos y un niño"""
    consulta = Consulta(date.today()+timedelta(days=5),
                            noches=5,
                            adultos = 2,
                            ninyos = 1,
                           )
    dispo = Disponibilidad(consulta)
    dispo.obtener_disponibilidad()
    form = BuscarForm()
    return direct_to_template(request, template='recepcion/disponibilidad.html',
                              extra_context={'dispo': dispo, 'consulta':consulta, 'form':form})


def disponibilidad(request):
    """Buscador de disponibilidad"""
    data = {}
    if request.method == "POST":
        form = BuscarForm(request.POST)
        if form.is_valid():
            # procesamos la dispo
            hotel = form.cleaned_data['hotel']
            noches = form.cleaned_data['fecha_salida'] - form.cleaned_data['fecha_llegada']
            # Eliminamos los bebés de la dispo
            nins = 0
            for x in range(1, form.cleaned_data['nins_d1']+1):
                if form.cleaned_data['edad_nin%s_d1' % x ]>2:
                    nins += 1
            consulta = Consulta(
               inicio = form.cleaned_data['fecha_llegada'],
               noches = noches.days,
               adultos = form.cleaned_data['adultos_d1'],
               ninyos = nins,
               hotel = hotel
            )
            dispo = Disponibilidad(consulta)
            dispo.obtener_disponibilidad()
            data['consulta'] = consulta
            data['dispo'] = dispo
    else:
        form = BuscarForm()
    data['form'] = form
    return direct_to_template(request, template='recepcion/disponibilidad.html', extra_context=data)

src/templates/recepcion/buscador.html
{% extends "base_recepcion.html" %}
{% load recepcion_tags %}
{% block page_css %}
<link type="text/css" href="{{MEDIA_URL}}css/redmond/jquery-ui-1.8.custom.css" rel="stylesheet" />	
{% endblock page_css %}
{% block content %}
<div class="span-6 last">
  Buscador

<form action="." method="post" accept-charset="utf-8">
         <div id="hotel" class="span-6 last">
           <label for="hotel">{{form.hotel.label}}</label>
           {{form.hotel}}
          </div>
          <div id="selector_fino" class="span-6 last">
            <label for="id_fecha_llegada">{{form.fecha_llegada.label}}</label>
            {{form.fecha_llegada}}
            <label for="id_fecha_salida">{{form.fecha_salida.label}}</label><br/>
            {{form.fecha_salida}}
          </div>
          <div id="habitaciones" class="span-6 last">
            <label for="id_habitaciones">Habitaciones</label>
            {{form.habitaciones}}
            </div>
            <div id="distri_1">
              Adultos {{form.adultos_d1}}
              Niños {{form.nins_d1}}
              <div id="edad_nin_d1" class="span-6 last" style="display:none;">
                Edad de los niños en Habitación 1 <br/>
                {{form.edad_nin1_d1}}
                {{form.edad_nin2_d1}}
                {{form.edad_nin3_d1}}
              </div>
           </div>
          <div id="distri_2" style="display:none;">
              Adultos {{form.adultos_d2}}
              Niños {{form.nins_d2}}
                <div id="edad_nin_d2" class="span-6 last" style="display:none;">
                Edad de los niños en Habitación 2 <br/>
                {{form.edad_nin1_d2}}
                {{form.edad_nin2_d2}}
                {{form.edad_nin3_d2}}
               </div>
              </div>
          <div id="distri_3" style="display:none;"> 
              Adultos {{form.adultos_d3}}
              Niños {{form.nins_d3}} 
             <div id="edad_nin_d3" class="span-6 last" style="display:none;">
                Edad de los niños en Habitación 3 <br/>
                {{form.edad_nin1_d3}}
                {{form.edad_nin2_d3}}
                {{form.edad_nin3_d3}}
              </div>
            </div>
         <p><input type="submit" value="Buscar &rarr;"></p>
        </form>
      </div>
      {% endblock content %}

      {% block page_js %}
      <script type="text/javascript">
        var MEDIA_URL = "{{MEDIA_URL}}";
      </script>
      <script type="text/javascript" src="{{MEDIA_URL}}js/jquery/jquery-ui-1.8.custom.min.js"></script>
      <script type="text/javascript" src="{{MEDIA_URL}}js/buscador.js"></script>
{% endblock page_js %}

src/templates/recepcion/contrato_hotel.html
{% extends "base_recepcion.html" %}
{% block content %}
{% with object as hotel %}
  {% include "recepcion/contrato.html" %}
{% endwith %}
{% endblock content %}

src/templates/recepcion/disponibilidad.html
{% extends "base_recepcion.html" %}
{% load recepcion_tags %}
{% block page_css %}
<link type="text/css" href="{{MEDIA_URL}}css/redmond/jquery-ui-1.8.custom.css" rel="stylesheet" />	
{% endblock page_css %}
{% block content %}
<div class="span-6">
  Buscador
<form action="." method="post" accept-charset="utf-8">
         <div id="hotel" class="span-6 last">
           <label for="hotel">{{form.hotel.label}}</label>
           {{form.hotel}}
          </div>
          <div id="selector_fino" class="span-6 last">
            <label for="id_fecha_llegada">{{form.fecha_llegada.label}}</label>
            {{form.fecha_llegada}}
            <label for="id_fecha_salida">{{form.fecha_salida.label}}</label><br/>
            {{form.fecha_salida}}
          </div>
          <div id="habitaciones" class="span-6 last">
            <label for="id_habitaciones">Habitaciones</label>
            {{form.habitaciones}}
            </div>
            <div id="distri_1">
              Adultos {{form.adultos_d1}}
              Niños {{form.nins_d1}}
              <div id="edad_nin_d1" class="span-6 last" style="display:none;">
                Edad de los niños en Habitación 1 <br/>
                {{form.edad_nin1_d1}}
                {{form.edad_nin2_d1}}
                {{form.edad_nin3_d1}}
              </div>
           </div>
          <div id="distri_2" style="display:none;">
              Adultos {{form.adultos_d2}}
              Niños {{form.nins_d2}}
                <div id="edad_nin_d2" class="span-6 last" style="display:none;">
                Edad de los niños en Habitación 2 <br/>
                {{form.edad_nin1_d2}}
                {{form.edad_nin2_d2}}
                {{form.edad_nin3_d2}}
               </div>
              </div>
          <div id="distri_3" style="display:none;"> 
              Adultos {{form.adultos_d3}}
              Niños {{form.nins_d3}} 
             <div id="edad_nin_d3" class="span-6 last" style="display:none;">
                Edad de los niños en Habitación 3 <br/>
                {{form.edad_nin1_d3}}
                {{form.edad_nin2_d3}}
                {{form.edad_nin3_d3}}
              </div>
            </div>
            <div id="captcha">
                {{form.captcha}}
            </div>
         <p><input type="submit" value="Buscar &rarr;"></p>
        </form>
      </div>
      <div class="span-12 last">
      {% if consulta %}
        <h2>Consulta</h2>
        <dl>
          <dt>Fecha Entrada:</dt><dd>{{consulta.entrada}}</dd>
          <dt>Fecha Salida:</dt><dd>{{consulta.salida}}</dd>
          <dt>Noches:</dt><dd>{{consulta.noches}}</dd>
          <dt>Habitaciones:</dt><dd>{{consulta.num_habitaciones}}</dd>
          <dt>Tipo Habitación:</dt><dd>{% if consulta.tipo_habitacion %}{{consulta.tipo_habitacion}}{% else %}Cualquiera{% endif %}</dd>
          <dt>Adultos:</dt><dd>{{consulta.adultos}}</dd>
          <dt>Niños (Los menores de 2 años se consideran bebés):</dt><dd>{{consulta.ninyos}}</dd>
          <dt>Hotel:</dt><dd>{% if consulta.hotel %} {{consulta.hotel.nombre}} {% else %} Todos {% endif %}</dd>
        </dl>
        {% for k, hotel in dispo.hoteles.items %}
        <h2>Hotel: {{hotel.slug}}</h2>
        <table>
        {% for kh, habitacion in hotel.habitaciones.items %}
        <tr><td>{{kh}}</td><td>{{habitacion.tipo}}</td><td>{{habitacion.regimen}}</td><td>{{habitacion.precio}}&nbsp;€
       </td></tr>
        {% endfor %}
      </table>
        <h5>Suplementos</h5>
        <table>
            {% for ts, supl in hotel.suplementos_regimen.items %}
            <tr><td>{{supl.1}}:</td><td>{{supl.0}} €</td></tr>
            {% endfor %}
         </table> 
        {% empty %}
        <p>No se encontró disponibilidad</p>
        {% endfor %}
      {% endif %}
{% endblock content %}
{% block page_js %}
      <script type="text/javascript">
        var MEDIA_URL = "{{MEDIA_URL}}";
      </script>
      <script type="text/javascript" src="{{MEDIA_URL}}js/jquery/jquery-ui-1.8.custom.min.js"></script>
      <script type="text/javascript" src="{{MEDIA_URL}}js/buscador.js"></script>
{% endblock page_js %}

src/templates/recepcion/hotel_list.html
{% extends "base_recepcion.html" %}
{% load recepcion_tags %}
{% block content %}
{% for hotel in object_list %}
  {% include "recepcion/contrato.html" %}
{% endfor %}
{% endblock content %}

src/templates/recepcion/hoteles.html
{% extends "base_recepcion.html" %}
{% load recepcion_tags %}
{% block content %}
<ul>
{% for hotel in object_list %}
<li>{{hotel.nombre}} <a href="{% url contrato-hotel hotel.slug %}">Ver contrato</a></li>
{% endfor %}
</ul>
{% endblock content %}